Lab07/matriculasLabs/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.tabla_asignaturas,name="index"),
    path('generar-pdf/', views.generar_pdf, name='generar_pdf'),
    path('send-email/', views.send_email, name='send_email'),
]

Lab07/registro/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('matriculasLabs.urls')),
]

Lab07/matriculasLabs/models.py
from django.db import models

class Docente(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Estudiante(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Asignatura(models.Model):
    name = models.CharField(max_length=50)
    docentes = models.ManyToManyField(Docente)

    def __str__(self):
        return self.name

class Delegado(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    asignatura = models.ForeignKey(Asignatura, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.estudiante.name} - {self.asignatura.name}"

    class Meta:
        unique_together = ('asignatura',)

Lab07/matriculasLabs/views.py
# EMAIL

from django.core.mail import send_mail

# pdf

from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from io import BytesIO

# Vista para la lista

from django.shortcuts import render
from .models import Asignatura

def tabla_asignaturas(request):
    asignaturas = Asignatura.objects.all()
    return render(request, 'lista.html', {'asignaturas': asignaturas})


# función para el renderizado en pdf 

def generar_pdf(request):
    template_path = 'lista.html'
    asignaturas = Asignatura.objects.all()
    context = {'asignaturas': asignaturas}
    template = get_template(template_path)
    html = template.render(context)

    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)

    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')

    return HttpResponse('Error al generar el PDF: {}'.format(pdf.err), status=500)

def send_email(request):
    asunto = 'Laboratios EPIS'
    mensaje_obligatorio = 'Buen día'
    correo = 'jccahuanala@unsa.edu.pe'

    send_mail(
        asunto,
        mensaje_obligatorio,
        correo,
        ['joshep.antony.ccl7427@gmail.com',],
        fail_silently=False)
    
    return render(request, 'email.html')

Lab07/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Send Email</title>
</head>
<body>
  <h1>ENVIO EXITOSO</h1>
</body>
</html>

Lab07/templates/lista.html
<!DOCTYPE html>
<html>
<head>
    <title>Tabla de Asignaturas de Laboratios</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1>Tabla de Asignaturas de Laboratios</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Asignatura</th>
                    <th>Docente Encargado</th>
                    <th>Delegado</th>
                </tr>
            </thead>
            <tbody>
                {% for asignatura in asignaturas %}
                <tr>
                    <td>{{ asignatura.name }}</td>
                    <td>
                        {% for docente in asignatura.docentes.all %}
                        {{ docente.name }}
                        {% endfor %}
                    </td>
                    <td>
                        {% for delegado in asignatura.delegado_set.all %}
                        {{ delegado.estudiante.name }}
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'generar_pdf' %}" class="btn btn-secondary">Formato PDF</a>
        <a href="{% url 'send_email' %}" class="btn btn-secondary">Enviar email</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>